AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rust Lambda REST API

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: provided.al2023
    Architectures:
      - arm64
    Environment:
      Variables:
        RUST_LOG: info
        OTEL_SERVICE_NAME: api-lambda
        OTEL_EXPORTER_OTLP_ENDPOINT: ""

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/bootstrap/
      Handler: bootstrap
      Events:
        RootPath:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        ProxyPath:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
