AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rust Lambda REST API

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: provided.al2023
    Architectures:
      - arm64
    Environment:
      Variables:
        OTEL_SERVICE_NAME: {{project-name}}
        OTEL_EXPORTER_OTLP_ENDPOINT: ""

Resources:
{% if enable_oidc %}
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: OidcAuthorizer
        Authorizers:
          OidcAuthorizer:
            AuthorizationScopes:
              - openid
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: "{{oidc_issuer_url}}"
              audience:
                - "{{oidc_audience}}"

{% endif %}
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/bootstrap/
      Handler: bootstrap
      Events:
        RootPath:
          Type: HttpApi
          Properties:
{% if enable_oidc %}
            ApiId: !Ref HttpApi
{% endif %}
            Path: /
            Method: ANY
        ProxyPath:
          Type: HttpApi
          Properties:
{% if enable_oidc %}
            ApiId: !Ref HttpApi
{% endif %}
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
{% if enable_oidc %}
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
{% else %}
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
{% endif %}
